import { useEffect, useState } from 'react';
import { MailCheck, PhoneCall } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { supabase } from '@/lib/supabase';
import { useAuthStore } from '@/stores/authStore';
import { showToast } from '@/stores/uiStore';
export function AccountVerificationCard(){const {user,refreshUser}=useAuthStore();const [emailEnabled,setEmailEnabled]=useState(false);const [phoneEnabled,setPhoneEnabled]=useState(false);const [code,setCode]=useState('');const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);useEffect(()=>{supabase.from('platform_settings').select('setting_key,setting_value').in('setting_key',['enable_email_verification','enable_phone_verification']).then(({data})=>{for(const x of data||[]){if(x.setting_key==='enable_email_verification')setEmailEnabled(x.setting_value==='true');if(x.setting_key==='enable_phone_verification')setPhoneEnabled(x.setting_value==='true')}})},[]);if(!emailEnabled&&!phoneEnabled)return null;const send=async()=>{setBusy(true);try{const {data,error}=await supabase.functions.invoke('send-email-verification');if(error)throw error;if(data?.disabled)throw new Error('Email verification is currently disabled.');setSent(true);showToast('success','Code sent','Check your email for the 6-digit code.')}catch(e:any){showToast('error','Could not send code',e.message)}finally{setBusy(false)}};const verify=async()=>{setBusy(true);try{const {error}=await supabase.functions.invoke('verify-account-code',{body:{channel:'email',code}});if(error)throw error;await refreshUser();setSent(false);setCode('');showToast('success','Email verified','Your email address is now verified.')}catch(e:any){showToast('error','Verification failed',e.message)}finally{setBusy(false)}};return <Card><CardContent className="space-y-4 p-5"><div><p className="font-semibold text-gray-900">Account verification</p><p className="text-sm text-gray-500">Verification channels enabled by Dispatch NG.</p></div>{emailEnabled&&<div className="rounded-xl border p-4"><div className="flex items-center gap-3"><MailCheck className="h-5 w-5 text-emerald-600"/><div className="flex-1"><p className="font-medium">Email</p><p className="text-sm text-gray-500">{user?.email_verified_at?'Verified':user?.email}</p></div>{!user?.email_verified_at&&!sent&&<Button size="sm" onClick={send} disabled={busy}>Verify</Button>}</div>{sent&&!user?.email_verified_at&&<div className="mt-3 flex gap-2"><Input inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="6-digit code"/><Button onClick={verify} disabled={busy||code.length!==6}>Confirm</Button></div>}</div>}{phoneEnabled&&<div className="flex items-center gap-3 rounded-xl border p-4"><PhoneCall className="h-5 w-5 text-slate-600"/><div><p className="font-medium">Phone</p><p className="text-sm text-gray-500">{user?.phone_verified_at?'Verified':'SMS verification is enabled; provider setup is required.'}</p></div></div>}</CardContent></Card>}
