import { Link } from 'react-router-dom';
import { BrandMark } from '@/components/BrandMark';
type PublicInfoProps = { page: keyof typeof content };
const content = {
  help: { title: 'Help Center', items: [['How do I request a delivery?', 'Create an account, open your dashboard and submit a delivery request. Review the agreed amount and delivery details before confirming.'], ['How do I pay?', 'Fund your wallet using the payment options shown in your account. If Paystack confirms a charge but your balance does not update, keep the transaction reference and contact support.'], ['Where can I get help?', 'Sign in and open Support to raise a ticket about a delivery, payment, or account issue.']] },
  disputes: { title: 'Disputes & Refunds', items: [['Report a delivery issue', 'Open the delivery in your account and contact Support with the delivery reference and supporting evidence.'], ['What happens next?', 'Our team reviews the delivery record, payment status, rider updates, and evidence before making a decision.'], ['Refund timing', 'Refund eligibility and processing depend on the delivery status, payment method, and outcome of the review. Do not treat a refund as confirmed until your wallet or payment provider reflects it.']] },
  safety: { title: 'Safety Guidelines', items: [['For customers', 'Use the platform to book and pay for deliveries. Share accurate pickup and destination details, and avoid sharing passwords or verification codes.'], ['For riders', 'Confirm pickup details, protect customer information, follow applicable road safety rules, and provide delivery proof where required.'], ['Report concerns', 'Report suspicious activity, damaged items, or unsafe conduct through the in-app Support area.']] },
  terms: { title: 'Platform Terms', items: [['Using Dispatch NG', 'Dispatch NG provides a platform for customers to request deliveries and riders to accept jobs. Account holders are responsible for accurate information and lawful use.'], ['Payments and disputes', 'Wallet funding, escrow settlement, cancellations, and refunds are subject to the applicable transaction status and dispute review.'], ['Important', 'This page is a preliminary information summary, not a finalized legal agreement. Publish a professionally reviewed Terms of Service before a broad commercial launch.']] },
  privacy: { title: 'Privacy Overview', items: [['Information collected', 'The platform may process account details, contact information, delivery details, verification documents, and transaction records to provide its services.'], ['How information is used', 'Information is used for account management, deliveries, safety checks, support, payments, and legally required recordkeeping.'], ['Important', 'This is a preliminary privacy overview. Before a broad launch, publish a complete policy specifying retention periods, legal bases, processors, rights requests, and a verified privacy contact.']] },
  cookies: { title: 'Cookies & Storage', items: [['Essential storage', 'The website uses browser storage and session mechanisms necessary for authentication and core functionality.'], ['Preferences', 'Some preferences, such as appearance and app settings, may be retained to improve the experience.'], ['Important', 'Review the deployed site’s actual analytics, cookies, and third-party services before publishing a final cookie notice.']] },
} as const;
export function PublicInfoPage({page}:PublicInfoProps) {
  const info=content[page];
  return <div className="min-h-screen bg-slate-50 text-slate-900">
    <header className="border-b bg-white"><div className="mx-auto flex max-w-4xl items-center justify-between px-5 py-4"><Link to="/"><BrandMark imageClassName="max-h-12 max-w-[155px] object-contain" /></Link><Link to="/" className="text-sm font-semibold text-emerald-700">Back to home</Link></div></header>
    <main className="mx-auto max-w-4xl px-5 py-12 sm:py-20"><p className="mb-3 text-sm font-semibold uppercase tracking-widest text-emerald-700">Dispatch NG</p><h1 className="mb-8 text-3xl font-bold sm:text-4xl">{info.title}</h1><div className="space-y-5">{info.items.map(([heading,body])=><section key={heading} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-2 text-lg font-semibold">{heading}</h2><p className="leading-7 text-slate-600">{body}</p></section>)}</div><div className="mt-10 rounded-2xl bg-slate-900 p-6 text-white"><h2 className="font-semibold">Need help with your account or delivery?</h2><p className="mt-2 text-sm text-slate-300">Sign in and use Support to contact our team.</p><Link to="/login" className="mt-4 inline-flex rounded-xl bg-emerald-600 px-5 py-3 text-sm font-semibold text-white">Sign in</Link></div></main></div>;
}
