import { useState } from 'react';
import { supabase } from '@/lib/supabase';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
export function AdminReconciliationPage(){
 const [reference,setReference]=useState('');const [busy,setBusy]=useState(false);const [result,setResult]=useState<any>(null);
 async function inspect(){setBusy(true);setResult(null);try{const {data,error}=await supabase.functions.invoke('admin-reconcile-paystack',{body:{reference:reference.trim()}});if(error)throw error;setResult(data);}catch(e){setResult({error:e instanceof Error?e.message:String(e)});}finally{setBusy(false)}}
 return <div className="mx-auto max-w-3xl space-y-6"><div><h1 className="text-2xl font-bold text-slate-900">Paystack Reconciliation</h1><p className="mt-2 text-slate-600">Inspect a Paystack reference against wallet transaction records. This tool is read-only and does not alter balances.</p></div><div className="rounded-2xl border bg-white p-6 shadow-sm"><label htmlFor="paystack-ref" className="mb-2 block font-medium">Paystack reference</label><Input id="paystack-ref" value={reference} onChange={e=>setReference(e.target.value)} placeholder="Enter transaction reference"/><Button disabled={busy||reference.trim().length<5} onClick={inspect} className="mt-4 bg-emerald-700 text-white">{busy?'Checking...':'Verify payment & inspect ledger'}</Button>{result&&<div role="status" className="mt-5 space-y-2 rounded-xl bg-slate-50 p-4 text-sm">{result.error?<p className="text-red-700">{result.error}</p>:<><p><strong>Paystack:</strong> {result.paystack_status}</p><p><strong>Amount:</strong> {result.currency} {Number(result.amount||0).toLocaleString()}</p><p><strong>Customer profile ID:</strong> {result.profile_id||'Not available'}</p><p><strong>Matching ledger entries:</strong> {result.ledger_count}</p><p className="text-amber-700">Read-only check. No wallet credit or refund has been issued. Review discrepancies before taking action.</p></>}</div>}</div><p className="text-sm text-slate-500">A missing ledger record alone does not prove that a credit is missing. Confirm the wallet balance and transaction history before any manual adjustment.</p></div>
}
