import { useEffect, useState } from 'react';
import { BadgeCheck, CheckCircle, ExternalLink, RefreshCw, User, XCircle } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { supabase } from '@/lib/supabase';
import { showToast } from '@/stores/uiStore';

type Item = { id:string; profile_id:string; document_type:string; document_number:string|null; document_image_url:string|null; selfie_image_url:string|null; verification_status:string; rejection_reason:string|null; created_at:string; profile?:{full_name?:string;email?:string;phone?:string;avatar_url?:string;user_type?:string}|null; documentSigned?:string; selfieSigned?:string };

export function AdminVerificationsPage(){
 const [items,setItems]=useState<Item[]>([]); const [filter,setFilter]=useState<'pending'|'verified'|'rejected'>('pending'); const [selected,setSelected]=useState<Item|null>(null); const [reason,setReason]=useState(''); const [rejectOpen,setRejectOpen]=useState(false); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false);
 const load=async()=>{setLoading(true); try { const {data,error}=await supabase.from('kyc_records').select('*, profile:profile_id(full_name,email,phone,avatar_url,user_type)').eq('verification_status',filter).order('created_at',{ascending:false}); if(error)throw error; setItems((data as any[])||[]);}catch(e:any){showToast('error','Could not load verifications',e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[filter]);
 const open=async(item:Item)=>{ let documentSigned, selfieSigned; if(item.document_image_url){ const {data}=await supabase.storage.from('kyc-documents').createSignedUrl(item.document_image_url,300); documentSigned=data?.signedUrl;} if(item.selfie_image_url){const {data}=await supabase.storage.from('kyc-documents').createSignedUrl(item.selfie_image_url,300); selfieSigned=data?.signedUrl;} setSelected({...item,documentSigned,selfieSigned}); };
 const decide=async(status:'verified'|'rejected')=>{if(!selected)return;setBusy(true);try{const now=new Date().toISOString(); const {data:{user:admin}}=await supabase.auth.getUser(); const {error}=await supabase.from('kyc_records').update({verification_status:status,verified_at:status==='verified'?now:null,verified_by:status==='verified'?admin?.id:null,rejection_reason:status==='rejected'?(reason.trim()||'Verification could not be approved. Please review your documents and resubmit.'):null,updated_at:now}).eq('id',selected.id);if(error)throw error; await supabase.from('profiles').update({verification_status:status,updated_at:now}).eq('id',selected.profile_id); if(selected.profile?.user_type==='rider'){await supabase.from('rider_profiles').update({verification_status:status==='verified'?'verified':'rejected',updated_at:now}).eq('profile_id',selected.profile_id);} await supabase.from('notifications').insert({profile_id:selected.profile_id,type:'kyc_status',title:status==='verified'?'Identity verification approved':'Identity verification needs attention',message:status==='verified'?'Your Dispatch NG identity verification has been approved.':(reason.trim()||'Your verification was not approved. Please review and resubmit.'),is_read:false}); showToast('success',status==='verified'?'Verification approved':'Verification rejected',`${selected.profile?.full_name||'User'} has been updated.`); setSelected(null);setRejectOpen(false);setReason('');await load();}catch(e:any){showToast('error','Action failed',e.message)}finally{setBusy(false)}};
 return <div className="space-y-5"><div className="flex items-start justify-between gap-3"><div><h1 className="text-2xl font-bold text-gray-900">Identity Verifications</h1><p className="text-gray-500">Review lightweight KYC for customers and riders.</p></div><Button variant="outline" size="sm" onClick={load}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></div>
 <Tabs value={filter} onValueChange={v=>setFilter(v as any)}><TabsList><TabsTrigger value="pending">Pending</TabsTrigger><TabsTrigger value="verified">Verified</TabsTrigger><TabsTrigger value="rejected">Rejected</TabsTrigger></TabsList></Tabs>
 {loading?<div className="space-y-3">{[1,2,3].map(i=><Card key={i} className="h-24 animate-pulse"/>)}</div>:items.length===0?<Card className="border-dashed"><CardContent className="p-8 text-center"><BadgeCheck className="mx-auto mb-3 h-10 w-10 text-emerald-500"/><p className="font-semibold">No {filter} verifications</p></CardContent></Card>:<div className="space-y-3">{items.map(item=><Card key={item.id} onClick={()=>open(item)} className="cursor-pointer hover:shadow-sm"><CardContent className="flex items-center gap-3 p-4"><div className="flex h-11 w-11 items-center justify-center overflow-hidden rounded-full bg-emerald-50">{item.profile?.avatar_url?<img src={item.profile.avatar_url} className="h-full w-full object-cover"/>:<User className="h-5 w-5 text-emerald-600"/>}</div><div className="min-w-0 flex-1"><p className="font-semibold text-gray-900">{item.profile?.full_name||'Unnamed user'}</p><p className="truncate text-sm text-gray-500">{item.profile?.email||'No email'} · <span className="capitalize">{item.profile?.user_type||'user'}</span></p></div><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-medium capitalize text-gray-700">{item.verification_status}</span></CardContent></Card>)}</div>}
 <Dialog open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>Review identity</DialogTitle></DialogHeader>{selected&&<div className="space-y-4"><div><p className="text-lg font-semibold">{selected.profile?.full_name}</p><p className="text-sm text-gray-500">{selected.profile?.email} · {selected.profile?.phone||'No phone'}</p></div><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-gray-50 p-3"><p className="text-xs text-gray-500">Account</p><p className="font-medium capitalize">{selected.profile?.user_type}</p></div><div className="rounded-xl bg-gray-50 p-3"><p className="text-xs text-gray-500">Document</p><p className="font-medium uppercase">{selected.document_type.replace('_',' ')}</p></div><div className="col-span-2 rounded-xl bg-gray-50 p-3"><p className="text-xs text-gray-500">Document number</p><p className="font-medium">{selected.document_number||'Not supplied'}</p></div></div><div className="grid grid-cols-2 gap-3">{selected.documentSigned&&<a href={selected.documentSigned} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-2 rounded-xl border p-3 text-sm font-medium text-emerald-700">View ID <ExternalLink className="h-4 w-4"/></a>}{selected.selfieSigned&&<a href={selected.selfieSigned} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-2 rounded-xl border p-3 text-sm font-medium text-teal-700">View selfie <ExternalLink className="h-4 w-4"/></a>}</div>{selected.verification_status==='pending'&&<div className="flex gap-3"><Button disabled={busy} onClick={()=>decide('verified')} className="flex-1 bg-emerald-600 hover:bg-emerald-700"><CheckCircle className="mr-2 h-4 w-4"/>Approve</Button><Button disabled={busy} variant="outline" onClick={()=>setRejectOpen(true)} className="flex-1 border-red-200 text-red-600"><XCircle className="mr-2 h-4 w-4"/>Reject</Button></div>}</div>}</DialogContent></Dialog>
 <Dialog open={rejectOpen} onOpenChange={setRejectOpen}><DialogContent><DialogHeader><DialogTitle>Reject verification</DialogTitle></DialogHeader><Textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Tell the user what needs to be corrected…" rows={4}/><div className="flex gap-3"><Button variant="outline" className="flex-1" onClick={()=>setRejectOpen(false)}>Cancel</Button><Button variant="destructive" className="flex-1" disabled={busy} onClick={()=>decide('rejected')}>Reject</Button></div></DialogContent></Dialog>
 </div>
}
